import matplotlib.pyplot as plt
A = 106
C = 1283
M = 6075
N = 1000

I = [0]
index = []

for i in range(1,N+1):
    index.append(i)
    I.append(-1)

I[1] = 1

for j in range(1,N):
    I[j+1] = (A*I[j] + C) % M

plt.xlabel('Ij')
plt.ylabel('Ij+1')
plt.title('Ij+1 vs Ij')
plt.plot(I[1:N], I[2:])
plt.show()

"""

#### q1(b) - From the graph we can deduce that, it is actually forming a web plot called "cobweb plot" 
and the sequence of values generated by the iterative function is random and confusing.
The output is Highly dependent on initial values, thus a small change in that will result in a 
completely different plot
"""